export const BASE = '/sariq-bola-finance/'
export const LOGO = BASE + 'logo.png'
export const BRANCH_ORDER = ['PROSPEKT','MAKRO','QOQON','TOSHKENT']
export const ACCOUNTS = ['Naqd','Hisob raqam']
export const MODULES = [
  'dashboard','salesAnalytics','order','orderReports','cash',
  'operation','history','reports','employees','payroll',
  'payrollArchive','categories','users','chat','profile'
]
export const ROLE_LABELS = {
  ADMIN:'Admin', RAHBAR:'Rahbar', BOSH_MANAGER:'Bosh menejer',
  FILIAL_MANAGER:'Filial menejer', SMENA_MANAGER:'Smena menejer', BUXGALTER:'Buxgalter'
}
export const OP_TYPE    = { INCOME:'Kirim', EXPENSE:'Chiqim' }
export const CASH_ST    = { PENDING:'PENDING', APPROVED:'APPROVED' }
export const SALARY_T   = { HOURLY:'hourly', MONTHLY:'monthly' }
export const TG_FN      = 'telegram-send'
export const SIGN_IN_RPC = 'finance_sign_in'
export const HASH_RPC    = 'finance_hash_password'
export const PERIOD_PAGES = [
  'dashboard','salesAnalytics','orderReports','history','reports','payrollArchive'
]
export const ROLE_MODULES = {
  RAHBAR:       ['dashboard','salesAnalytics','orderReports','history','reports','payrollArchive','chat','profile'],
  BOSH_MANAGER: ['dashboard','salesAnalytics','orderReports','history','reports','chat','profile'],
  FILIAL_MANAGER:['dashboard','salesAnalytics','orderReports','reports','chat','profile'],
  SMENA_MANAGER: ['order','chat','profile'],
  BUXGALTER:    ['dashboard','cash','operation','history','reports','employees','payroll','payrollArchive','chat','profile']
}

export const TEXT = {
  uz:{
    dashboard:'Dashboard', salesAnalytics:'Savdo analitika', order:'Smena order',
    orderReports:'Filial orderlari', cash:'Inkassatsiya', operation:'Kirim / Chiqim',
    history:'Operatsiyalar', reports:'Hisobotlar', employees:'Xodimlar',
    payroll:'Oylik hisoblash', payrollArchive:'Oylik arxivi', categories:'Kategoriyalar',
    users:'Foydalanuvchilar', chat:'Chat', profile:'Profil', logout:'Chiqish',
    welcome:'Xush kelibsiz', refresh:'Yangilash', save:'Saqlash', create:'Yaratish',
    edit:'Tahrirlash', delete:"O'chirish", cancel:'Bekor qilish', start:'Boshlanish',
    end:'Tugash', branch:'Filial', all:'Umumiy', cashBalance:'Naqd balans',
    bankBalance:'Hisob raqam balans', incomeChart:"Kirimlar kategoriyalar bo'yicha",
    expenseChart:"Chiqimlar kategoriyalar bo'yicha", branchSales:"Filiallar bo'yicha savdo",
    trend:'Savdo trendi', totalSales:'Jami savdo', growth:"O'sish / pasayish",
    noData:"Ma'lumot yo'q", date:'Sana', shift:'Smena', total:'Jami savdo',
    uzcard:'Uzcard', humo:'Humo', rahmat:'Rahmat', rxmt:'RXMT', uzum:'Uzum', yandex:'Yandex',
    expense:'Xarajat', gum:'Jvachka soni', cashAmount:'Naqd summa',
    type:'Tur', account:'Hisob', category:'Kategoriya', amount:'Summa', note:'Izoh',
    income:'Kirim', outcome:'Chiqim', fullName:'Ism-familya', login:'Login',
    password:'Parol', role:'Lavozim', access:'Dostup', position:'Lavozim',
    hireDate:'Ishga kirgan sana', salaryType:'Ish haqi turi', hourly:'Soatbay',
    monthly:'Oylik', hourlyRate:'Soatiga', monthlySalary:'Oylik stavka',
    workedHours:'Ishlagan soat', extraHours:"Qo'shimcha soat", tax:"Daromad solig'i",
    lunch:'Tushlik', penalty:'Jarima', advance:'Avans', bonus:'Premiya',
    cashPaid:'Naqd berildi', cardPaid:'Plastik berildi', remaining:'Qoldiq',
    signature:'Imzo', exportExcel:'Excel yuklab olish', uploadPhoto:'Rasm yuklash',
    send:'Yuborish', chooseUser:'Foydalanuvchi tanlang', actions:'Amal', status:'Status',
    expected:'Kutilgan', accepted:'Qabul', difference:'Farq',
    categoryNameNeeded:'Kategoriya nomi kerak', categoryAdded:"Kategoriya qo'shildi",
    categoryUpdated:'Kategoriya yangilandi', categoryDeleted:"Kategoriya o'chirildi",
    saved:'Saqlandi', deleted:"O'chirildi", chooseBranch:'Filial tanlang',
    adminOnly:"Faqat admin amalga oshira oladi", loginRequired:'Login va parol kiriting',
    loginError:'Login yoki parol xato', confirmDelete:"Rostdan o'chirasizmi?",
    userLoginBusy:'Bu login band', userNameRequired:'Ism va login majburiy',
    passwordRequired:'Yangi foydalanuvchi uchun parol majburiy',
    employeeNameRequired:'Xodim ismi kerak', payrollPeriodRequired:'Oylik davrini tanlang',
    payrollStartEndError:"Boshlanish sanasi tugash sanasidan katta bo'lmasin",
    payrollNoEmployees:"Filial tanlang yoki xodim yo'q",
    categoryRequired:'Kategoriya va summa majburiy', orderTotalRequired:'Jami savdo majburiy',
    alreadyApproved:'Bu inkassatsiya allaqachon tasdiqlangan',
    backupAdminOnly:'Faqat admin backup olishi mumkin',
    importNoRows:'Import uchun mos qator topilmadi',
    importOrdersNoRows:'Import uchun mos order topilmadi',
    noSelected:"Tanlangan qator yo'q", telegramSaved:'Telegram sozlamalari saqlandi',
    telegramTest:'Yuborilmoqda...', telegramOk:'✅ Test xabari yuborildi!',
    telegramErr:'❌ Telegram xatosi: ',
  },
  ru:{
    dashboard:'Дашборд', salesAnalytics:'Аналитика продаж', order:'Сменный отчет',
    orderReports:'Отчеты филиалов', cash:'Инкассация', operation:'Приход / Расход',
    history:'Операции', reports:'Отчеты', employees:'Сотрудники',
    payroll:'Расчет зарплаты', payrollArchive:'Архив зарплаты', categories:'Категории',
    users:'Пользователи', chat:'Чат', profile:'Профиль', logout:'Выход',
    welcome:'Добро пожаловать', refresh:'Обновить', save:'Сохранить', create:'Создать',
    edit:'Изменить', delete:'Удалить', cancel:'Отмена', start:'Начало', end:'Конец',
    branch:'Филиал', all:'Общий', cashBalance:'Наличные', bankBalance:'Расчетный счет',
    incomeChart:'Приходы по категориям', expenseChart:'Расходы по категориям',
    branchSales:'Продажи по филиалам', trend:'Динамика продаж', totalSales:'Общая продажа',
    growth:'Рост / снижение', noData:'Нет данных', date:'Дата', shift:'Смена',
    total:'Общая продажа', uzcard:'Uzcard', humo:'Humo', rahmat:'Rahmat',
    rxmt:'RXMT', uzum:'Uzum', yandex:'Yandex', expense:'Расход', gum:'Кол-во жвачки',
    cashAmount:'Сумма наличными', type:'Тип', account:'Счет', category:'Категория',
    amount:'Сумма', note:'Комментарий', income:'Приход', outcome:'Расход',
    fullName:'Ф.И.О', login:'Логин', password:'Пароль', role:'Должность', access:'Доступ',
    position:'Должность', hireDate:'Дата приема', salaryType:'Тип оплаты',
    hourly:'Почасовая', monthly:'Месячная', hourlyRate:'За час', monthlySalary:'Оклад',
    workedHours:'Рабочие часы', extraHours:'Доп. часы', tax:'Подоходный налог',
    lunch:'Обед', penalty:'Штраф', advance:'Аванс', bonus:'Премия',
    cashPaid:'Наличными', cardPaid:'На карту', remaining:'Остаток', signature:'Подпись',
    exportExcel:'Скачать Excel', uploadPhoto:'Загрузить фото', send:'Отправить',
    chooseUser:'Выберите пользователя', actions:'Действие', status:'Статус',
    expected:'Ожидалось', accepted:'Принято', difference:'Разница',
    categoryNameNeeded:'Введите название', categoryAdded:'Категория добавлена',
    categoryUpdated:'Категория обновлена', categoryDeleted:'Категория удалена',
    saved:'Сохранено', deleted:'Удалено', chooseBranch:'Выберите филиал',
    adminOnly:'Только администратор', loginRequired:'Введите логин и пароль',
    loginError:'Неверный логин или пароль', confirmDelete:'Вы уверены?',
    userLoginBusy:'Логин занят', userNameRequired:'Имя и логин обязательны',
    passwordRequired:'Для нового пользователя пароль обязателен',
    employeeNameRequired:'Введите имя сотрудника', payrollPeriodRequired:'Выберите период',
    payrollStartEndError:'Начало не может быть позже конца',
    payrollNoEmployees:'Выберите филиал или нет сотрудников',
    categoryRequired:'Категория и сумма обязательны', orderTotalRequired:'Общая продажа обязательна',
    alreadyApproved:'Инкассация уже подтверждена',
    backupAdminOnly:'Только администратор может делать бэкап',
    importNoRows:'Нет подходящих строк', importOrdersNoRows:'Нет подходящих отчётов',
    noSelected:'Нет выбранных строк', telegramSaved:'Настройки Telegram сохранены',
    telegramTest:'Отправка...', telegramOk:'✅ Тест отправлен!',
    telegramErr:'❌ Ошибка Telegram: ',
  },
  cy:{
    dashboard:'Дашборд', salesAnalytics:'Савдо аналитика', order:'Смена ордер',
    orderReports:'Филиал ордерлари', cash:'Инкассация', operation:'Кирим / Чиқим',
    history:'Операциялар', reports:'Ҳисоботлар', employees:'Ходимлар',
    payroll:'Ойлик ҳисоблаш', payrollArchive:'Ойлик архиви', categories:'Категориялар',
    users:'Фойдаланувчилар', chat:'Чат', profile:'Профил', logout:'Чиқиш',
    welcome:'Хуш келибсиз', refresh:'Янгилаш', save:'Сақлаш', create:'Яратиш',
    edit:'Таҳрирлаш', delete:'Ўчириш', cancel:'Бекор қилиш', start:'Бошланиш',
    end:'Тугаш', branch:'Филиал', all:'Умумий', cashBalance:'Нақд баланс',
    bankBalance:'Ҳисоб рақам баланс', incomeChart:'Киримлар категориялар бўйича',
    expenseChart:'Чиқимлар категориялар бўйича', branchSales:'Филиаллар бўйича савдо',
    trend:'Савдо тренди', totalSales:'Жами савдо', growth:'Ўсиш / пасайиш',
    noData:'Маълумот йўқ', date:'Сана', shift:'Смена', total:'Жами савдо',
    uzcard:'Uzcard', humo:'Humo', rahmat:'Rahmat', rxmt:'RXMT', uzum:'Uzum', yandex:'Yandex',
    expense:'Харажат', gum:'Жвачка сони', cashAmount:'Нақд сумма',
    type:'Тур', account:'Ҳисоб', category:'Категория', amount:'Сумма', note:'Изоҳ',
    income:'Кирим', outcome:'Чиқим', fullName:'Исм-фамилия', login:'Логин',
    password:'Парол', role:'Лавозим', access:'Доступ', position:'Лавозим',
    hireDate:'Ишга кирган сана', salaryType:'Иш ҳақи тури', hourly:'Соатбай',
    monthly:'Ойлик', hourlyRate:'Соатига', monthlySalary:'Ойлик ставка',
    workedHours:'Ишлаган соат', extraHours:'Қўшимча соат', tax:'Даромад солиғи',
    lunch:'Тушлик', penalty:'Жарима', advance:'Аванс', bonus:'Премия',
    cashPaid:'Нақд берилди', cardPaid:'Пластик берилди', remaining:'Қолдиқ',
    signature:'Имзо', exportExcel:'Excel юклаб олиш', uploadPhoto:'Расм юклаш',
    send:'Юбориш', chooseUser:'Фойдаланувчи танланг', actions:'Амал', status:'Статус',
    expected:'Кутилган', accepted:'Қабул', difference:'Фарқ',
    categoryNameNeeded:'Категория номи керак', categoryAdded:'Категория қўшилди',
    categoryUpdated:'Категория янгиланди', categoryDeleted:'Категория ўчирилди',
    saved:'Сақланди', deleted:'Ўчирилди', chooseBranch:'Филиал танланг',
    adminOnly:'Фақат админ', loginRequired:'Логин ва парол киритинг',
    loginError:'Логин ёки парол хато', confirmDelete:'Ростдан ўчирасизми?',
    userLoginBusy:'Бу логин банд', userNameRequired:'Исм ва логин мажбурий',
    passwordRequired:'Янги фойдаланувчи учун парол мажбурий',
    employeeNameRequired:'Ходим исми керак', payrollPeriodRequired:'Ойлик даврини танланг',
    payrollStartEndError:"Бошланиш санаси тугаш санасидан катта бўлмасин",
    payrollNoEmployees:"Филиал танланг ёки ходим йўқ",
    categoryRequired:'Категория ва сумма мажбурий', orderTotalRequired:'Жами савдо мажбурий',
    alreadyApproved:'Бу инкассация аллақачон тасдиқланган',
    backupAdminOnly:'Фақат админ бэкап ола олади',
    importNoRows:'Импорт учун мос қатор топилмади',
    importOrdersNoRows:'Импорт учун мос ордер топилмади',
    noSelected:"Танланган қатор йўқ", telegramSaved:'Telegram созламалари сақланди',
    telegramTest:'Юборилмоқда...', telegramOk:'✅ Тест юборилди!',
    telegramErr:'❌ Telegram хатоси: ',
  }
}